# This script archives student home folders and then removes the Linux users.
# It reads the users CSV generated by create_students.sh.
# CSV format:
# student_id,username
#
# Example:
# sudo ./remove_students.sh 2023_fall_users.csv

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: sudo ./remove_students.sh year_semester_users.csv"
    exit 1
fi

USERS_FILE="$1"

if [ ! -f "$USERS_FILE" ]; then
    echo "Error: Users CSV file '$USERS_FILE' was not found."
    exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: Please run this script with sudo."
    exit 1
fi

USERS_BASENAME="$(basename "$USERS_FILE")"

if [[ "$USERS_BASENAME" != *_users.csv ]]; then
    echo "Error: Users CSV file name must end with '_users.csv'."
    exit 1
fi

SEMESTER_NAME="${USERS_BASENAME%_users.csv}"
ARCHIVE_DIR="$HOME/archives"
ARCHIVE_FILE="$ARCHIVE_DIR/${SEMESTER_NAME}.tar"

mkdir -p "$ARCHIVE_DIR"

users_to_remove=()
home_folders=()
missing_home=0

# Read usernames from the CSV file and skip the header.
while IFS=',' read -r student_id username; do
    username="$(echo "$username" | xargs)"

    if [ -z "$username" ]; then
        continue
    fi

    if id "$username" > /dev/null 2>&1; then
        users_to_remove+=("$username")

        if [ -d "/home/$username" ]; then
            home_folders+=("/home/$username")
        else
            echo "Warning: Home folder for '$username' was not found."
            missing_home=1
        fi
    else
        echo "Warning: User '$username' does not exist."
    fi
done < <(tail -n +2 "$USERS_FILE")

if [ "${#users_to_remove[@]}" -eq 0 ]; then
    echo "No existing users were found to remove."
    exit 0
fi

if [ "$missing_home" -eq 1 ]; then
    echo "Error: One or more home folders were missing."
    echo "No archive was created and no users were removed."
    exit 1
fi

if [ "${#home_folders[@]}" -eq 0 ]; then
    echo "Error: No home folders were found, so no archive can be created."
    echo "No users were removed."
    exit 1
fi

echo "The following users will be archived and removed:"
printf ' - %s\n' "${users_to_remove[@]}"
echo
read -r -p "Type YES to continue: " confirmation

if [ "$confirmation" != "YES" ]; then
    echo "Cancelled. No users were removed."
    exit 0
fi

# Create the compressed archive before deleting any accounts.
if tar -czf "$ARCHIVE_FILE" "${home_folders[@]}"; then
    if [ ! -s "$ARCHIVE_FILE" ]; then
        echo "Error: Archive file was created but is empty."
        echo "No users were removed."
        exit 1
    fi
else
    echo "Error: Archive was not created successfully."
    echo "No users were removed."
    exit 1
fi

echo "Archive created successfully: $ARCHIVE_FILE"

# Only remove users after the archive has been created successfully.
for username in "${users_to_remove[@]}"; do
    userdel -r "$username"
    echo "Removed user '$username'."
done

echo "Done."
